#!/bin/bash

GREEN="\033[0;32m"
RED="\033[0;31m"
NO_COLOR="\033[0m"

QARMC=../../qarmc5/qarmc

if [ ! -x osummarizer ]; then
    make osummarizer
fi

if [ ! -x $QARMC ]; then
    echo "Could not find executable $QARMC"
fi

for f in `ls tests/pos/*.of`; do
    (   set -e
        echo -n "$f ... "
        ./osummarizer $f ${f%.of}.qarmc >/dev/null
        $QARMC ${f%.of}.qarmc >/tmp/qarmc.out
        grep 'program is correct' /tmp/qarmc.out >/dev/null 2>1
        echo -e ${GREEN}PASSED$NO_COLOR
    ) || echo -e ${RED}FAILED$NO_COLOR
done
